typography_spectrum: 0.6494201442218469
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.5692042780453617
  lightness: 0.22151678802685276
  saturation: 0.9723906275971175
  rhythmicContrast: 0.49445062653530425
github: true
layout_spectrum: 0.2919329657137283
analytics:
  google: UA-99971719-1
author:
  name: Trevor Mears
  email: trevor@shiftframe.com
  url: 'http://trevormears.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9a7f8cc5-1235-4b41-ab2f-5f7f61643b36.png
name: Trevor Mears | Las Vegas SEO Expert & Digital Marketing Consultant
url: 'https://trevormears.com'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: My Process
    id: d0036f63-d71d-41f8-a826-5bbb95b8ce5e
    type: content
  - name: What is SEO?
    id: 4fe3fa03-9bac-4afb-a1bd-e6ac09ed0bb6
    type: content
  - name: Shiftframe
    url: 'https://shiftframe.com'
    type: external
  - name: Post Launch
    url: 'https://postlaunch.co'
    type: external
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/trevormears'
    type: external
  - name: Las Vegas SEO
    id: 162ec4a0-1a78-4a5c-a47c-92f49cf84a9d
    type: content
title: Las Vegas SEO Expert & Digital Marketing Consultant Trevor Mears
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4831393e-1e42-452e-8339-8e8b0d9263f2.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4831393e-1e42-452e-8339-8e8b0d9263f2.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Las Vegas SEO Expert & Digital Marketing Consultant Trevor Mears.  Contact
  Trevor today for a FREE website analysis to see how your site is currently
  performing in search engines.
purpose:
  - type: contact
    url: 'mailto:trevor@shiftframe.com'
    label: Contact me
  - type: contact
    url: 'tel:7025189420'
    label: Call (702) 518-9420
